// Recettes de base pour le métier tailleur.
// Placeholder minimal : on pourra enrichir avec de vraies ressources.
export const tailleurRecipes = [
  {
    id: "coiffe_corbeau_air",
    label: "Coiffe du corbeau (Air)",
    level: 1,
    category: "coiffe",
    inputs: [
      { itemId: "plume_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "coiffe_corbeau_air", qty: 1 },
    xpGain: 25,
  },
  {
    id: "coiffe_corbeau_eau",
    label: "Coiffe du corbeau (Eau)",
    level: 1,
    category: "coiffe",
    inputs: [
      { itemId: "plume_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "coiffe_corbeau_eau", qty: 1 },
    xpGain: 25,
  },
  {
    id: "coiffe_corbeau_feu",
    label: "Coiffe du corbeau (Feu)",
    level: 1,
    category: "coiffe",
    inputs: [
      { itemId: "plume_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "coiffe_corbeau_feu", qty: 1 },
    xpGain: 25,
  },
  {
    id: "coiffe_corbeau_terre",
    label: "Coiffe du corbeau (Terre)",
    level: 1,
    category: "coiffe",
    inputs: [
      { itemId: "plume_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "coiffe_corbeau_terre", qty: 1 },
    xpGain: 25,
  },
  {
    id: "cape_corbeau_air",
    label: "Cape du corbeau (Air)",
    level: 1,
    category: "cape",
    inputs: [
      { itemId: "plume_corbeau", qty: 4 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "cape_corbeau_air", qty: 1 },
    xpGain: 30,
  },
  {
    id: "cape_corbeau_eau",
    label: "Cape du corbeau (Eau)",
    level: 1,
    category: "cape",
    inputs: [
      { itemId: "plume_corbeau", qty: 4 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "cape_corbeau_eau", qty: 1 },
    xpGain: 30,
  },
  {
    id: "cape_corbeau_feu",
    label: "Cape du corbeau (Feu)",
    level: 1,
    category: "cape",
    inputs: [
      { itemId: "plume_corbeau", qty: 4 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "cape_corbeau_feu", qty: 1 },
    xpGain: 30,
  },
  {
    id: "cape_corbeau_terre",
    label: "Cape du corbeau (Terre)",
    level: 1,
    category: "cape",
    inputs: [
      { itemId: "plume_corbeau", qty: 4 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "cape_corbeau_terre", qty: 1 },
    xpGain: 30,
  },
  {
    id: "coiffe_gobgob",
    label: "Casque du GobGob",
    level: 13,
    category: "coiffe",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "coiffe_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "cape_gobgob",
    label: "Cape du GobGob",
    level: 12,
    category: "cape",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "cape_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "coiffe_goush",
    label: "Cagoule du Goush",
    level: 16,
    category: "coiffe",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "coiffe_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "cape_goush",
    label: "Cape du Goush",
    level: 15,
    category: "cape",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "cape_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "coiffe_liburion",
    label: "Coiffe du Liburion",
    level: 18,
    category: "coiffe",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "coiffe_liburion", qty: 1 },
    xpGain: 35,
  },
  {
    id: "cape_liburion",
    label: "Cape du Liburion",
    level: 17,
    category: "cape",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "cape_liburion", qty: 1 },
    xpGain: 35,
  },
];
