// Recettes de base pour le métier cordonnier (placeholder).
export const cordonnierRecipes = [
  {
    id: "bottes_corbeau_air",
    label: "Bottes du corbeau (Air)",
    level: 1,
    category: "bottes",
    inputs: [
      { itemId: "patte_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "bottes_corbeau_air", qty: 1 },
    xpGain: 25,
  },
  {
    id: "bottes_corbeau_eau",
    label: "Bottes du corbeau (Eau)",
    level: 1,
    category: "bottes",
    inputs: [
      { itemId: "patte_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "bottes_corbeau_eau", qty: 1 },
    xpGain: 25,
  },
  {
    id: "bottes_corbeau_feu",
    label: "Bottes du corbeau (Feu)",
    level: 1,
    category: "bottes",
    inputs: [
      { itemId: "patte_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "bottes_corbeau_feu", qty: 1 },
    xpGain: 25,
  },
  {
    id: "bottes_corbeau_terre",
    label: "Bottes du corbeau (Terre)",
    level: 1,
    category: "bottes",
    inputs: [
      { itemId: "patte_corbeau", qty: 3 },
      { itemId: "bec_corbeau", qty: 1 },
    ],
    output: { itemId: "bottes_corbeau_terre", qty: 1 },
    xpGain: 25,
  },
  {
    id: "ceinture_corbeau_air",
    label: "Ceinture du corbeau (Air)",
    level: 1,
    category: "ceinture",
    inputs: [
      { itemId: "patte_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 2 },
    ],
    output: { itemId: "ceinture_corbeau_air", qty: 1 },
    xpGain: 30,
  },
  {
    id: "ceinture_corbeau_eau",
    label: "Ceinture du corbeau (Eau)",
    level: 1,
    category: "ceinture",
    inputs: [
      { itemId: "patte_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 2 },
    ],
    output: { itemId: "ceinture_corbeau_eau", qty: 1 },
    xpGain: 30,
  },
  {
    id: "ceinture_corbeau_feu",
    label: "Ceinture du corbeau (Feu)",
    level: 1,
    category: "ceinture",
    inputs: [
      { itemId: "patte_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 2 },
    ],
    output: { itemId: "ceinture_corbeau_feu", qty: 1 },
    xpGain: 30,
  },
  {
    id: "ceinture_corbeau_terre",
    label: "Ceinture du corbeau (Terre)",
    level: 1,
    category: "ceinture",
    inputs: [
      { itemId: "patte_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 2 },
    ],
    output: { itemId: "ceinture_corbeau_terre", qty: 1 },
    xpGain: 30,
  },
  {
    id: "bottes_gobgob",
    label: "Bottes du GobGob",
    level: 9,
    category: "bottes",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "bottes_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "ceinture_gobgob",
    label: "Ceinture du GobGob",
    level: 10,
    category: "ceinture",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "ceinture_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "bottes_goush",
    label: "Sandales du Goush",
    level: 12,
    category: "bottes",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "bottes_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "ceinture_goush",
    label: "Ceinture du Goush",
    level: 13,
    category: "ceinture",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "ceinture_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "bottes_liburion",
    label: "Chaussures du Liburion",
    level: 14,
    category: "bottes",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "bottes_liburion", qty: 1 },
    xpGain: 35,
  },
  {
    id: "ceinture_liburion",
    label: "Ceinture du Liburion",
    level: 15,
    category: "ceinture",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "ceinture_liburion", qty: 1 },
    xpGain: 35,
  },
];
