export default {
  id: "cazard",
  label: "Cazard",
  textureKey: "cazard",
  spritePath: "assets/monsters/Cazard/rotations/south-west.png",
  animation: {
    prefix: "cazard",
    basePath: "assets/monsters/Cazard/animations/walk-4-frames",
    frameCount: 4,
  },
  render: {
    originX: 0.55,
    originY: 0.9,
    offsetY: 0,
  },
  baseLevel: 4,
  levelMin: 3,
  levelMax: 6,
  statsOverrides: {
    hpMax: 35,
    hp: 35,
    pa: 7,
    pm: 3,
    agilite: 8,
    initiative: 7,
  },
  spells: ["griffure", "projectile_epineux"],
  loot: [
    { itemId: "peau_cazard", min: 1, max: 1, dropRate: 0.3 },
    { itemId: "queue_cazard", min: 1, max: 1, dropRate: 0.35 },
  ],
  xpReward: 90,
  goldRewardMin: 12,
  goldRewardMax: 31,
};
