export default {
  id: "cazard",
  label: "Cazard",
  textureKey: "cazard",
  spritePath: "assets/monsters/Cazard/rotations/south-west.png",
  render: {
    originX: 0.55,
    originY: 0.9,
    offsetY: 0,
  },
  baseLevel: 4,
  levelMin: 3,
  levelMax: 6,
  statsOverrides: {
    hpMax: 35,
    hp: 35,
    pa: 7,
    pm: 3,
    agilite: 8,
    initiative: 7,
  },
  spells: ["griffure", "projectile_epineux"],
  loot: [],
  xpReward: 90,
  goldRewardMin: 12,
  goldRewardMax: 31,
};
