export default {
  id: "cedre",
  label: "Cèdre",
  textureKey: "cedre",
  spritePath: "assets/monsters/Cedre/rotations/south-west.png",
  render: {
    originX: 0.5,
    originY: 1,
    offsetY: 0,
  },
  baseLevel: 10,
  levelMin: 7,
  levelMax: 11,
  statsOverrides: {
    hpMax: 80,
    hp: 80,
    pa: 8,
    pm: 3,
    force: 20,
    initiative: 6,
  },
  spells: ["aura_cedre", "souffle_cedre"],
  loot: [],
  xpReward: 290,
  goldRewardMin: 28,
  goldRewardMax: 70,
};
