export default {
  id: "chibone",
  label: "Chibone",
  textureKey: "chibone",
  spritePath: "assets/monsters/Chibone/rotations/south-west.png",
  render: {
    originX: 0.55,
    originY: 0.9,
    offsetY: 0,
  },
  baseLevel: 12,
  levelMin: 12,
  levelMax: 15,
  statsOverrides: {
    hpMax: 100,
    hp: 100,
    pa: 6,
    pm: 4,
    force: 20,
    agilite: 15,
    initiative: 35,
  },
  spells: ["machoire"],
  loot: [],
  xpReward: 900,
  goldRewardMin: 30,
  goldRewardMax: 45,
};
