export default {
  id: "corbeau",
  familyId: "corbeau",
  label: "Zéphorbeau",
  textureKey: "corbeau",
  // Nouveau sprite corbeau (spritesheet 4 frames).
  // Affiche la frame 0 par défaut (et permettra une anim plus tard).
  spritePath: "assets/monsters/corbeau/animation/corbeauWalkSouthWestGreen.png",
  combatAvatarPath: "assets/monsters/corbeau/sprite/SpriteCorbeauAir.png",
  spriteSheet: { frameWidth: 48, frameHeight: 48 },
  render: {
    originX: 0.45,
    originY: 1.2,
    offsetY: 0,
  },
  baseLevel: 1,
  levelMin: 1,
  levelMax: 4,
  statsOverrides: {
    hpMax: 25,
    hp: 25,
    initiative: 5,
    agilite: 5,
  },
  spells: ["bec_de_zephyr"],
  loot: [
    { itemId: "plume_corbeau", min: 1, max: 1, dropRate: 0.5 },
    { itemId: "patte_corbeau", min: 1, max: 1, dropRate: 0.5 },
    { itemId: "bec_corbeau", min: 1, max: 1, dropRate: 0.4 },
    {
      itemId: "essence_corbeau",
      min: 1,
      max: 1,
      dropRate: 0.1,
      requiresJob: "alchimiste",
      minJobLevel: 1,
    },
    { itemId: "poussiere_temporelle", min: 1, max: 1, dropRate: 0.03 },
    { itemId: "coiffe_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
    { itemId: "cape_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
    { itemId: "amulette_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
    { itemId: "ceinture_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
    { itemId: "bottes_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
    { itemId: "anneau_corbeau_air", min: 1, max: 1, dropRate: 0.04 },
  ],
  xpReward: 20,
  goldRewardMin: 8,
  goldRewardMax: 21,
};
