export default {
  id: "goush",
  label: "Goush",
  textureKey: "goush",
  spritePath: "assets/monsters/goush/south-west.png",
  animation: {
    prefix: "goush",
    basePath: "assets/monsters/goush/animations/running-4-frames",
    frameCount: 4,
  },
  render: {
    originX: 0.5,
    originY: 1,
    offsetY: 0,
  },
  baseLevel: 8,
  levelMin: 6,
  levelMax: 9,
  statsOverrides: {
    hpMax: 70,
    hp: 70,
    pa: 7,
    pm: 3,
    force: 24,
    initiative: 7,
  },
  spells: ["morsure", "bave_puante"],
  loot: [],
  xpReward: 220,
  goldRewardMin: 18,
  goldRewardMax: 40,
};
