export default {
  id: "gumgob",
  label: "Gumgob",
  textureKey: "gumgob",
  spritePath: "assets/monsters/Gumgob/rotations/south-west.png",
  animation: {
    prefix: "gumgob",
    basePath: "assets/monsters/Gumgob/animations/running-4-frames",
    frameCount: 4,
  },
  useDiagonalFacing: true,
  extraAnimations: {
    attack: {
      basePath: "assets/monsters/Gumgob/animations/lead-jab",
      directions: ["north-east", "north-west", "south-east", "south-west"],
      frameCount: 3,
      frameRate: 12,
      repeat: 0,
    },
    death: {
      basePath: "assets/monsters/Gumgob/animations/falling-back-death",
      directions: ["south-east"],
      frameCount: 7,
      frameRate: 10,
      repeat: 0,
    },
  },
  spellAnimations: {
    coup_de_massue: "attack",
  },
  deathAnimation: "death",
  render: {
    originX: 0.5,
    originY: 1.12,
    offsetY: 0,
  },
  baseLevel: 7,
  levelMin: 4,
  levelMax: 7,
  statsOverrides: {
    hpMax: 50,
    hp: 50,
    pa: 7,
    pm: 3,
    force: 14,
    initiative: 5,
  },
  spells: ["coup_de_massue", "jet_de_caillou"],
  loot: [
    { itemId: "peau_gobelin", min: 1, max: 1, dropRate: 0.4 },
  ],
  xpReward: 120,
  goldRewardMin: 15,
  goldRewardMax: 34,
};
