export default {
  id: "gumgob",
  label: "Gumgob",
  textureKey: "gumgob",
  spritePath: "assets/monsters/Gumgob/rotations/south-west.png",
  animation: {
    prefix: "gumgob",
    basePath: "assets/monsters/Gumgob/animations/running-4-frames",
    frameCount: 4,
  },
  render: {
    originX: 0.5,
    originY: 1.12,
    offsetY: 0,
  },
  baseLevel: 7,
  levelMin: 4,
  levelMax: 7,
  statsOverrides: {
    hpMax: 50,
    hp: 50,
    pa: 7,
    pm: 3,
    force: 14,
    initiative: 5,
  },
  spells: ["coup_de_massue", "jet_de_caillou"],
  loot: [],
  xpReward: 120,
  goldRewardMin: 15,
  goldRewardMax: 34,
};
