export default {
  id: "libarene",
  label: "Libarene",
  textureKey: "libarene",
  spritePath: "assets/monsters/Libarene/rotations/south-west.png",
  animation: {
    prefix: "libarene",
    basePath: "assets/monsters/Libarene/animations/running-4-frames",
    frameCount: 4,
    scale: 1.4,
  },
  render: {
    originX: 0.6,
    originY: 0.85,
    offsetY: 0,
  },
  baseLevel: 12,
  levelMin: 10,
  levelMax: 14,
  statsOverrides: {
    hpMax: 80,
    hp: 80,
    pa: 7,
    pm: 4,
    intelligence: 22,
    initiative: 8,
  },
  spells: ["taille_libarene", "griffure_libarene"],
  loot: [
    { itemId: "fourrure_liburion", min: 1, max: 1, dropRate: 0.3 },
  ],
  xpReward: 360,
  goldRewardMin: 16,
  goldRewardMax: 36,
};
