export default {
  id: "ondoreau",
  label: "Ondoreau",
  textureKey: "ondoreau",
  spritePath: "assets/monsters/corbeau/corbeauWalkSouthWestBlue.png",
  combatAvatarPath: "assets/monsters/corbeau/SpriteCorbeauEau.png",
  spriteSheet: { frameWidth: 48, frameHeight: 48 },
  render: {
    originX: 0.45,
    originY: 1.2,
    offsetY: 0,
  },
  statsOverrides: {
    hpMax: 25,
    hp: 25,
    initiative: 5,
    chance: 5,
  },
  spells: ["bec_ondoyant"],
  loot: [
    { itemId: "plume_corbeau", min: 1, max: 1, dropRate: 0.5 },
    { itemId: "patte_corbeau", min: 1, max: 1, dropRate: 0.5 },
    { itemId: "coiffe_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
    { itemId: "cape_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
    { itemId: "amulette_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
    { itemId: "ceinture_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
    { itemId: "bottes_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
    { itemId: "anneau_corbeau_eau", min: 1, max: 1, dropRate: 0.02 },
  ],
  xpReward: 20,
  goldRewardMin: 8,
  goldRewardMax: 21,
};
