export default {
  id: "senbone",
  label: "Senbone",
  textureKey: "senbone",
  spritePath: "assets/monsters/Senbone/rotations/south-west.png",
  render: {
    originX: 0.5,
    originY: 1,
    offsetY: 0,
  },
  baseLevel: 20,
  levelMin: 20,
  levelMax: 20,
  statsOverrides: {
    hpMax: 300,
    hp: 300,
    pa: 10,
    pm: 4,
    force: 50,
    initiative: 150,
  },
  spells: ["fissure", "solitude"],
  loot: [],
  xpReward: 8300,
  goldRewardMin: 60,
  goldRewardMax: 130,
};
