export default {
  id: "skelbone",
  label: "Skelbone",
  textureKey: "skelbone",
  spritePath: "assets/monsters/Skelbone/rotations/south-west.png",
  render: {
    originX: 0.5,
    originY: 1,
    offsetY: 0,
  },
  baseLevel: 12,
  levelMin: 13,
  levelMax: 16,
  statsOverrides: {
    hpMax: 125,
    hp: 125,
    pa: 7,
    pm: 4,
    agilite: 55,
    initiative: 50,
  },
  spells: ["maintendu"],
  loot: [],
  xpReward: 1200,
  goldRewardMin: 35,
  goldRewardMax: 50,
};
