// Recettes de base pour le métier bijoutier (placeholder).
export const bijoutierRecipes = [
  {
    id: "anneau_corbeau_air",
    label: "Anneau du corbeau (Air)",
    level: 1,
    category: "anneau",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 1 },
    ],
    output: { itemId: "anneau_corbeau_air", qty: 1 },
    xpGain: 25,
  },
  {
    id: "anneau_corbeau_eau",
    label: "Anneau du corbeau (Eau)",
    level: 1,
    category: "anneau",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 1 },
    ],
    output: { itemId: "anneau_corbeau_eau", qty: 1 },
    xpGain: 25,
  },
  {
    id: "anneau_corbeau_feu",
    label: "Anneau du corbeau (Feu)",
    level: 1,
    category: "anneau",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 1 },
    ],
    output: { itemId: "anneau_corbeau_feu", qty: 1 },
    xpGain: 25,
  },
  {
    id: "anneau_corbeau_terre",
    label: "Anneau du corbeau (Terre)",
    level: 1,
    category: "anneau",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "plume_corbeau", qty: 1 },
    ],
    output: { itemId: "anneau_corbeau_terre", qty: 1 },
    xpGain: 25,
  },
  {
    id: "amulette_corbeau_air",
    label: "Collier du corbeau (Air)",
    level: 1,
    category: "amulette",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "amulette_corbeau_air", qty: 1 },
    xpGain: 30,
  },
  {
    id: "amulette_corbeau_eau",
    label: "Collier du corbeau (Eau)",
    level: 1,
    category: "amulette",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "amulette_corbeau_eau", qty: 1 },
    xpGain: 30,
  },
  {
    id: "amulette_corbeau_feu",
    label: "Collier du corbeau (Feu)",
    level: 1,
    category: "amulette",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "amulette_corbeau_feu", qty: 1 },
    xpGain: 30,
  },
  {
    id: "amulette_corbeau_terre",
    label: "Collier du corbeau (Terre)",
    level: 1,
    category: "amulette",
    inputs: [
      { itemId: "bec_corbeau", qty: 2 },
      { itemId: "patte_corbeau", qty: 1 },
      { itemId: "essence_corbeau", qty: 1 },
    ],
    output: { itemId: "amulette_corbeau_terre", qty: 1 },
    xpGain: 30,
  },
  {
    id: "anneau_gobgob",
    label: "Anneau du GobGob",
    level: 11,
    category: "anneau",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "anneau_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "amulette_gobgob",
    label: "Collier du GobGob",
    level: 11,
    category: "amulette",
    inputs: [{ itemId: "peau_gobelin", qty: 1 }],
    output: { itemId: "amulette_gobgob", qty: 1 },
    xpGain: 25,
  },
  {
    id: "anneau_goush",
    label: "Anneau du Goush",
    level: 14,
    category: "anneau",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "anneau_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "amulette_goush",
    label: "Collier du Goush",
    level: 14,
    category: "amulette",
    inputs: [{ itemId: "peau_goush", qty: 1 }],
    output: { itemId: "amulette_goush", qty: 1 },
    xpGain: 30,
  },
  {
    id: "anneau_liburion",
    label: "Gants du Liburion",
    level: 16,
    category: "anneau",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "anneau_liburion", qty: 1 },
    xpGain: 35,
  },
  {
    id: "amulette_liburion",
    label: "Collier du Liburion",
    level: 16,
    category: "amulette",
    inputs: [{ itemId: "fourrure_liburion", qty: 1 }],
    output: { itemId: "amulette_liburion", qty: 1 },
    xpGain: 35,
  },
];
