export const questGiverNpcs = [
  {
    id: "papi_bucheron",
    name: "Papi",
    mapId: "Map1Andemia",
    tileX: 16,
    tileY: 12,
    textureKey: "npc_papi",
    spritePath: "assets/npc/papiSouth-west.png",
    type: "quest_giver",
    questIds: ["papi_corbeaux_1", "papi_meme_1"],
  },
  {
    id: "meme_village",
    name: "Mémé",
    mapId: "MapAndemia2",
    tileX: 16,
    tileY: 11,
    textureKey: "npc_meme",
    spritePath: "assets/npc/memeSouth-east.png",
    type: "quest_giver",
    questIds: [],
  },
  {
    id: "mentor_map5",
    name: "Maître",
    mapId: "MapAndemia5",
    tileX: 17,
    tileY: 17,
    textureKey: "npc_provisoire",
    spritePath: "assets/npc/Provisoiresouth-east.png",
    type: "quest_giver",
    questIds: [
      "mentor_epreuve_corbeaux_1",
      "mentor_epreuve_goush_liburion_1",
      "mentor_epreuve_aluineeks_1",
    ],
  },
];
