export const questGiverNpcs = [
  {
    id: "papi_bucheron",
    name: "Papi",
    mapId: "Map1Andemia",
    tileX: 16,
    tileY: 12,
    textureKey: "npc_papi",
    spritePath: "assets/npc/papiSouth-west.png",
    type: "quest_giver",
    questIds: ["andemia_intro_1"],
  },
  {
    id: "meme_village",
    name: "Meme",
    mapId: "MapTaverne",
    tileX: 15,
    tileY: 17,
    offsetX: 0,
    offsetY: 0,
    textureKey: "npc_meme",
    spritePath: "assets/npc/memeSouth-east.png",
    type: "quest_giver",
    questIds: ["andemia_intro_2"],
  },
  {
    id: "alchimiste_provisoire",
    name: "Alchimiste",
    mapId: "MapMaisonAlchimiste",
    tileX: 14,
    tileY: 15,
    textureKey: "npc_alchimiste",
    spritePath: "assets/npc/Alchimistesouth-east.png",
    type: "quest_giver",
    questIds: [],
  },
  {
    id: "mentor_map5",
    name: "Maitre",
    mapId: "MapAndemia5",
    tileX: 17,
    tileY: 17,
    textureKey: "npc_provisoire",
    spritePath: "assets/npc/Provisoiresouth-east.png",
    type: "quest_giver",
    questIds: [],
  },
  {
    id: "maire_albinos",
    name: "Maire Albinos",
    mapId: "MapMairie",
    tileX: 17,
    tileY: 13,
    textureKey: "npc_maire_albinos",
    spritePath: "assets/npc/MaireAlbinossouth-west.png",
    type: "quest_giver",
    questIds: [],
  },
  {
    id: "maire_albinos_marchand",
    name: "Maire Albinos",
    mapId: "MapAndemiaNouvelleVersion7",
    offsetX: 10,
    offsetY: -10,
    tileX: 12,
    tileY: 18,
    textureKey: "npc_maire_albinos_nw",
    spritePath: "assets/npc/Mairenorth-west.png",
    type: "npc",
    questIds: [],
    requireQuestId: "alchimiste_marchand_3",
    requireQuestState: "in_progress",
    requireQuestStageId: ["meet_maire_marchand", "return_to_maire"],
  },
  {
    id: "marchand_boutique",
    name: "Marchand",
    mapId: "MapAndemiaNouvelleVersion7",
    offsetX: 10,
    offsetY: -10,
    tileX: 11,
    tileY: 18,
    textureKey: "npc_marchand",
    spritePath: "assets/npc/Marchandsouth-east.png",
    type: "merchant",
    shopId: "boutique",
    questIds: [],
  },
  {
    id: "donjonaluineekspnj",
    name: "Gardien du donjon",
    mapId: "MapAndemiaNouvelleVersion9",
    tileX: 21,
    tileY: 15,
    scale: 1.3,
    textureKey: "npc_donjon_aluineeks",
    spritePath: "assets/npc/DonjonALuineeksPNJsouth-west.png",
    type: "npc",
    questIds: [],
  },
  {
    id: "donjonaluineekspnj_north",
    name: "Gardien du donjon",
    mapId: "MapAndemiaNouvelleVersion10",
    tileX: 18,
    tileY: 18,
    scale: 1.3,
    textureKey: "npc_donjon_aluineeks_north",
    spritePath: "assets/npc/gardiennorth.png",
    type: "npc",
    questIds: [],
    requireQuestId: "keeper_north_explosion_1",
    requireQuestState: "in_progress",
  },
  {
    id: "maire_albinos_north",
    name: "Maire",
    mapId: "MapAndemiaNouvelleVersion10",
    tileX: 16,
    tileY: 19,
    textureKey: "npc_maire_north",
    spritePath: "assets/npc/mairenorth.png",
    type: "npc",
    questIds: [],
    requireQuestId: "keeper_north_explosion_1",
    requireQuestState: "in_progress",
  },
];
