export const questGiverNpcs = [
  {
    id: "papi_bucheron",
    name: "Papi",
    mapId: "Map1Andemia",
    tileX: 16,
    tileY: 12,
    textureKey: "npc_papi",
    spritePath: "assets/npc/papiSouth-west.png",
    type: "quest_giver",
    questIds: ["andemia_intro_1"],
  },
  {
    id: "meme_village",
    name: "Meme",
    mapId: "MapTaverne",
    tileX: 15,
    tileY: 17,
    textureKey: "npc_meme",
    spritePath: "assets/npc/memeSouth-east.png",
    type: "quest_giver",
    questIds: ["andemia_intro_2", "andemia_intro_4"],
  },
  {
    id: "alchimiste_provisoire",
    name: "Alchimiste",
    mapId: "MapMaisonAlchimiste",
    tileX: 14,
    tileY: 15,
    textureKey: "npc_alchimiste",
    spritePath: "assets/npc/Alchimistesouth-east.png",
    type: "quest_giver",
    questIds: ["andemia_intro_3"],
  },
  {
    id: "mentor_map5",
    name: "Maitre",
    mapId: "MapAndemia5",
    tileX: 17,
    tileY: 17,
    textureKey: "npc_provisoire",
    spritePath: "assets/npc/Provisoiresouth-east.png",
    type: "quest_giver",
    questIds: [
      "mentor_epreuve_corbeaux_1",
      "mentor_epreuve_goush_liburion_1",
      "mentor_epreuve_aluineeks_1",
    ],
  },
  {
    id: "maire_albinos",
    name: "Maire Albinos",
    mapId: "MapMairie",
    tileX: 20,
    tileY: 20,
    textureKey: "npc_maire_albinos",
    spritePath: "assets/npc/MaireAlbinossouth-west.png",
    type: "quest_giver",
    questIds: ["maire_corbeaux_1", "maire_cazard_1"],
  },
];
