export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 900;
export const HUD_HEIGHT = 192; // hauteur réservée en bas pour le HUD
export const SHOW_GRID = true;  // passe à false pour cacher la grille
export const GRID_ALPHA = 0.65; // opacité de la grille debug (0..1)
export const BACKGROUND_COLOR = "#0b3059";
export const CAMERA_ZOOM = 1.3;
export const CAMERA_PADDING = 1000;
export const PLAYER_SPEED = 300;
