// Sorts réservés aux monstres.
// Même modèle que les sorts des joueurs, mais organisés par monstre.

export const monsterSpells = {
  corbeau: {
    coup_de_bec: {
      id: "coup_de_bec",
      label: "Coup de bec",
      paCost: 4,
      rangeMin: 1,
      rangeMax: 1, // corps a corps
      lineOfSight: true,
      zone: "cell",
      element: "agilite",
      damageMin: 5,
      damageMax: 9,
      description: "Un coup de bec rapide au corps a corps.",
    },
  },

  aluineeks: {
    fissure: {
      id: "fissure",
      label: "Fissure",
      paCost: 4,
      rangeMin: 1,
      rangeMax: 2, // 1 a 2 cases
      lineOfSight: true,
      zone: "cell", // la ligne est geree dans l'IA
      element: "terre",
      damageMin: 12,
      damageMax: 15,
      description: "Fissure de terre en ligne (1-2 cases).",
    },
  },

  goush: {
    morsure: {
      id: "morsure",
      label: "Morsure",
      paCost: 3,
      rangeMin: 1,
      rangeMax: 1,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      damageMin: 8,
      damageMax: 12,
      maxCastsPerTurn: 1,
      description: "Une morsure brutale au corps a corps.",
    },
    bave_puante: {
      id: "bave_puante",
      label: "Bave puante",
      paCost: 4,
      rangeMin: 1,
      rangeMax: 4,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      // Le sort n'inflige pas de degats immediats : il applique un poison.
      damageOnHit: false,
      damageMin: 0,
      damageMax: 0,
      cooldownTurns: 3,
      statusEffect: {
        id: "bave_puante",
        type: "poison",
        label: "Bave puante",
        turns: 2,
        damageMin: 5,
        damageMax: 9,
      },
      description:
        "Crache une bave terre (1-4 PO) et empoisonne la cible pendant 2 tours.",
    },
  },

  liburion: {
    eclat: {
      id: "eclat",
      label: "Eclat liburien",
      paCost: 4,
      rangeMin: 2,
      rangeMax: 4,
      lineOfSight: true,
      zone: "cell",
      element: "feu",
      damageMin: 10,
      damageMax: 14,
      castPattern: "line4",
      maxCastsPerTurn: 2,
      description: "Un eclat en ligne, a moyenne portee.",
    },
  },

  cazard: {
    griffure: {
      id: "griffure",
      label: "Griffure",
      paCost: 3,
      rangeMin: 1,
      rangeMax: 1,
      lineOfSight: true,
      zone: "cell",
      element: "agilite",
      damageMin: 8,
      damageMax: 12,
      maxCastsPerTurn: 2,
      description: "Un coup de griffes rapide au corps a corps.",
    },
    projectile_epineux: {
      id: "projectile_epineux",
      label: "Projectile épineux",
      paCost: 4,
      rangeMin: 2,
      rangeMax: 4,
      lineOfSight: true,
      zone: "cell",
      element: "agilite",
      damageMin: 10,
      damageMax: 14,
      cooldownTurns: 2,
      description: "Lance un projectile à moyenne portée (2-4 PO).",
    },
  },

  cedre: {
    ronce: {
      id: "ronce",
      label: "Frappe de ronce",
      paCost: 3,
      rangeMin: 1,
      rangeMax: 1,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      damageMin: 7,
      damageMax: 11,
      maxCastsPerTurn: 2,
      description: "Une ronce frappe au corps a corps.",
    },
    seve_toxique: {
      id: "seve_toxique",
      label: "Sève toxique",
      paCost: 4,
      rangeMin: 1,
      rangeMax: 4,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      damageOnHit: false,
      damageMin: 0,
      damageMax: 0,
      cooldownTurns: 3,
      statusEffect: {
        id: "seve_toxique",
        type: "poison",
        label: "Sève toxique",
        turns: 2,
        damageMin: 4,
        damageMax: 7,
      },
      description: "Empoisonne la cible pendant 2 tours (1-4 PO).",
    },
  },

  gumgob: {
    coup_de_massue: {
      id: "coup_de_massue",
      label: "Coup de massue",
      paCost: 4,
      rangeMin: 1,
      rangeMax: 1,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      damageMin: 11,
      damageMax: 15,
      maxCastsPerTurn: 1,
      description: "Une attaque lourde au corps a corps.",
    },
    jet_de_caillou: {
      id: "jet_de_caillou",
      label: "Jet de caillou",
      paCost: 3,
      rangeMin: 2,
      rangeMax: 5,
      lineOfSight: true,
      zone: "cell",
      element: "terre",
      damageMin: 7,
      damageMax: 10,
      maxCastsPerTurn: 2,
      description: "Lance un caillou à distance (2-5 PO).",
    },
  },
};
