// Définition des sorts du jeu.

export const spells = {
  // --- Animiste (slot "mage") ---
  rayon_astral: {
    id: "rayon_astral",
    icon: "assets/Icon/IconSortAnimiste/RayonAstral.png",
    label: "Rayon astral",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 6,
    lineOfSight: true,
    zone: "cell",
    element: "air",
    damageMin: 7,
    damageMax: 10,
    critChanceBasePct: 5,
    damageCritMin: 9,
    damageCritMax: 12,
    effects: [{ type: "damage" }],
    description: "Un rayon d'air condensé, précis et régulier.",
  },
  siphon_vital: {
    id: "siphon_vital",
    label: "Siphon vital",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 4,
    damageMax: 6,
    critChanceBasePct: 5,
    damageCritMin: 5,
    damageCritMax: 7,
    effects: [{ type: "damage" }, { type: "lifeSteal" }],
    maxCastsPerTurn: 2,
    description: "Draine la vie de la cible et soigne le lanceur.",
  },
  racines_ancestrales: {
    id: "racines_ancestrales",
    label: "Racines ancestrales",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 10,
    damageMax: 14,
    critChanceBasePct: 5,
    damageCritMin: 12,
    damageCritMax: 17,
    effects: [{ type: "patternDamage", pattern: "front_cross" }],
    castPattern: "line4",
    maxCastsPerTurn: 1,
    description:
      "Un appel des racines en ligne, qui frappe en croix sur l'impact.",
  },

  capture_essence: {
    id: "capture_essence",
    icon: "assets/Icon/IconSortAnimiste/CaptureEssence.png",
    label: "Capture d'essence",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "neutre",
    damageMin: 0,
    damageMax: 0,
    critChanceBasePct: 5,
    damageCritMin: 0,
    damageCritMax: 0,
    effects: [{ type: "capture", playerTurns: 2 }],
    cooldownTurns: 5,
    description:
      "Marque une cible pendant 2 tours. Si elle meurt dans ce délai, elle est capturée.",
  },

  invocation_capturee: {
    id: "invocation_capturee",
    icon: "assets/Icon/IconSortAnimiste/InvocationCapturer.png",
    label: "Invocation capturée",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 6,
    lineOfSight: false,
    zone: "cell",
    element: "neutre",
    damageMin: 0,
    damageMax: 0,
    critChanceBasePct: 5,
    damageCritMin: 0,
    damageCritMax: 0,
    effects: [{ type: "summonCaptured", cooldownAfterDeathTurns: 2 }],
    description:
      "Invoque le monstre capturé. Une seule invocation à la fois. Cooldown 2 tours après sa mort.",
  },

  // --- Tank ---
  punch_furtif: {
    id: "punch_furtif",
    label: "Punch furtif",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 11,
    damageMax: 14,
    critChanceBasePct: 5,
    damageCritMin: 13,
    damageCritMax: 17,
    effects: [{ type: "damage" }],
    description: "Un coup de poing terre, rapide et précis.",
  },
  traction_aerienne: {
    id: "traction_aerienne",
    label: "Traction aérienne",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "air",
    damageMin: 8,
    damageMax: 11,
    critChanceBasePct: 5,
    damageCritMin: 10,
    damageCritMax: 13,
    effects: [{ type: "damage" }, { type: "pullCasterToMelee" }],
    maxCastsPerTurn: 1,
    castPattern: "line4",
    description:
      "Lance un tir d'air en ligne, puis rapproche au corps à corps si la cible est touchée.",
  },
  punch_enflamme: {
    id: "punch_enflamme",
    label: "Punch enflammé",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 2,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 11,
    damageMax: 15,
    critChanceBasePct: 5,
    damageCritMin: 13,
    damageCritMax: 18,
    effects: [{ type: "patternDamage", pattern: "front_cross" }],
    maxCastsPerTurn: 2,
    castPattern: "line4",
    description: "Un punch de feu en ligne qui frappe en croix devant le lanceur.",
  },

  // --- Archer ---
  tir_simple: {
    id: "tir_simple",
    icon: "assets/Icon/IconSortArcher/TirSimple.png",
    label: "Tir simple",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "agilite",
    damageMin: 9,
    damageMax: 15,
    critChanceBasePct: 5,
    damageCritMin: 11,
    damageCritMax: 18,
    effects: [{ type: "damage" }],
    description: "Un tir de base à distance.",
  },
  fleche_carbonisee: {
    id: "fleche_carbonisee",
    icon: "assets/Icon/IconSortArcher/FlecheCarbonisé.png",
    label: "Flèche carbonisée",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 8,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 11,
    damageMax: 17,
    critChanceBasePct: 5,
    damageCritMin: 13,
    damageCritMax: 20,
    effects: [{ type: "damage" }],
    description: "Une flèche de feu plus puissante mais plus coûteuse.",
  },
  flumigene: {
    id: "flumigene",
    icon: "assets/Icon/IconSortArcher/Flumigene.png",
    label: "Flumigène",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 6,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 5,
    damageMax: 7,
    critChanceBasePct: 5,
    damageCritMin: 6,
    damageCritMax: 9,
    effects: [{ type: "damage" }, { type: "lifeSteal" }],
    maxCastsPerTurn: 2,
    description: "Une flèche d'eau à faible dégâts qui vole la vie.",
  },
  pointe_refoulante: {
    id: "pointe_refoulante",
    icon: "assets/Icon/IconSortArcher/TirSimple.png",
    label: "Pointe refoulante",
    paCost: 3,
    requiredLevel: 4,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    castPattern: "line4",
    zone: "cell",
    element: "terre",
    damageMin: 8,
    damageMax: 12,
    critChanceBasePct: 5,
    damageCritMin: 10,
    damageCritMax: 14,
    effects: [{ type: "damage" }, { type: "push", distance: 2 }],
    maxCastsPerTargetPerTurn: 1,
    maxCastsPerTurn: 2,
    description: "Tir terre qui repousse la cible de 2 cases.",
  },
  meche_empoisonnee: {
    id: "meche_empoisonnee",
    icon: "assets/Icon/IconSortArcher/Flumigene.png",
    label: "Meche empoisonnee",
    paCost: 3,
    requiredLevel: 8,
    rangeMin: 1,
    rangeMax: 7,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageOnHit: false,
    damageMin: 7,
    damageMax: 11,
    critChanceBasePct: 5,
    damageCritMin: 9,
    damageCritMax: 13,
    effects: [{ type: "status", useSpellStatus: true }],
    statusEffect: {
      id: "meche_empoisonnee",
      type: "poison",
      label: "Meche empoisonnee",
      turns: 2,
      damageMin: 7,
      damageMax: 11,
    },
    maxCastsPerTargetPerTurn: 1,
    maxCastsPerTurn: 2,
    description: "Empoisonne la cible pendant 2 tours (feu).",
  },

  // --- Eryon ---
  recharge_flux: {
    id: "recharge_flux",
    icon: "assets/Icon/IconSortEryon/RechargeDeFlux.png",
    label: "Recharge de Flux",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 6,
    damageMax: 8,
    critChanceBasePct: 5,
    damageCritMin: 7,
    damageCritMax: 10,
    effects: [{ type: "damage" }],
    maxCastsPerTurn: 3,
    eryonCharges: { element: "feu", chargeGain: 1 },
    description: "Dégâts Feu légers et +1 charge Feu.",
  },
  surcharge_instable: {
    id: "surcharge_instable",
    icon: "assets/Icon/IconSortEryon/SurchargeRunique.png",
    label: "Surcharge instable",
    paCost: 5,
    requiredLevel: 1,
    rangeMin: 2,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 14,
    damageMax: 18,
    critChanceBasePct: 5,
    damageCritMin: 17,
    damageCritMax: 21,
    effects: [{ type: "patternDamage", pattern: "cross1" }],
    maxCastsPerTurn: 1,
    cooldownTurns: 3,
    eryonCharges: { element: "feu", chargeGain: 1 },
    description:
      "Croix (taille 1). Consomme jusqu'à 5 charges Feu : +10% dégâts par charge.",
  },
  stabilisation_flux: {
    id: "stabilisation_flux",
    icon: "assets/Icon/IconSortEryon/StabilisationDeFlux.png",
    label: "Stabilisation de Flux",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 6,
    damageMax: 8,
    critChanceBasePct: 5,
    damageCritMin: 7,
    damageCritMax: 10,
    effects: [{ type: "damage" }],
    maxCastsPerTurn: 3,
    eryonCharges: { element: "eau", chargeGain: 1 },
    description: "Dégâts Eau légers et +1 charge Eau.",
  },
};
