// Définition des sorts du jeu.

export const spells = {
  // --- Animiste (slot "mage") ---
  rayon_astral: {
    id: "rayon_astral",
    label: "Rayon astral",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 6,
    lineOfSight: true,
    zone: "cell",
    element: "air",
    damageMin: 7,
    damageMax: 10,
    description: "Un rayon d'air condensé, précis et régulier.",
  },
  siphon_vital: {
    id: "siphon_vital",
    label: "Siphon vital",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 4,
    damageMax: 6,
    lifeSteal: true,
    maxCastsPerTurn: 2,
    description: "Draine la vie de la cible et soigne le lanceur.",
  },
  racines_ancestrales: {
    id: "racines_ancestrales",
    label: "Racines ancestrales",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 10,
    damageMax: 14,
    castPattern: "line4",
    effectPattern: "front_cross",
    maxCastsPerTurn: 1,
    description:
      "Un appel des racines en ligne, qui frappe en croix sur l'impact.",
  },

  capture_essence: {
    id: "capture_essence",
    label: "Capture d'essence",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "neutre",
    damageMin: 0,
    damageMax: 0,
    cooldownTurns: 5,
    capture: { playerTurns: 2 },
    description:
      "Marque une cible pendant 2 tours. Si elle meurt dans ce délai, elle est capturée.",
  },

  invocation_capturee: {
    id: "invocation_capturee",
    label: "Invocation capturée",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 6,
    lineOfSight: false,
    zone: "cell",
    element: "neutre",
    damageMin: 0,
    damageMax: 0,
    summon: { cooldownAfterDeathTurns: 2 },
    description:
      "Invoque le monstre capturé. Une seule invocation à la fois. Cooldown 2 tours après sa mort.",
  },

  // --- Tank ---
  punch_furtif: {
    id: "punch_furtif",
    label: "Punch furtif",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 11,
    damageMax: 14,
    description: "Un coup de poing terre, rapide et précis.",
  },
  traction_aerienne: {
    id: "traction_aerienne",
    label: "Traction aérienne",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "air",
    damageMin: 8,
    damageMax: 11,
    maxCastsPerTurn: 1,
    castPattern: "line4",
    pullCasterToMeleeOnHit: true,
    description:
      "Lance un tir d'air en ligne, puis rapproche au corps à corps si la cible est touchée.",
  },
  punch_enflamme: {
    id: "punch_enflamme",
    label: "Punch enflammé",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 2,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 11,
    damageMax: 15,
    maxCastsPerTurn: 2,
    castPattern: "line4",
    effectPattern: "front_cross",
    description: "Un punch de feu en ligne qui frappe en croix devant le lanceur.",
  },

  // --- Archer ---
  tir_simple: {
    id: "tir_simple",
    label: "Tir simple",
    paCost: 3,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "agilite",
    damageMin: 9,
    damageMax: 15,
    description: "Un tir de base à distance.",
  },
  fleche_carbonisee: {
    id: "fleche_carbonisee",
    label: "Flèche carbonisée",
    paCost: 4,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 8,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 11,
    damageMax: 17,
    description: "Une flèche de feu plus puissante mais plus coûteuse.",
  },
  flumigene: {
    id: "flumigene",
    label: "Flumigène",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 1,
    rangeMax: 6,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 5,
    damageMax: 7,
    lifeSteal: true,
    maxCastsPerTurn: 2,
    description: "Une flèche d'eau à faible dégâts qui vole la vie.",
  },

  // --- Eryon ---
  recharge_flux: {
    id: "recharge_flux",
    label: "Recharge de Flux",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 6,
    damageMax: 8,
    maxCastsPerTurn: 3,
    eryonCharges: { element: "feu", chargeGain: 1 },
    description: "Dégâts Feu légers et +1 charge Feu.",
  },
  surcharge_instable: {
    id: "surcharge_instable",
    label: "Surcharge instable",
    paCost: 5,
    requiredLevel: 1,
    rangeMin: 2,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 14,
    damageMax: 18,
    maxCastsPerTurn: 1,
    cooldownTurns: 3,
    effectPattern: "cross1",
    eryonCharges: { element: "feu", chargeGain: 1 },
    description:
      "Croix (taille 1). Consomme jusqu'à 5 charges Feu : +10% dégâts par charge.",
  },
  stabilisation_flux: {
    id: "stabilisation_flux",
    label: "Stabilisation de Flux",
    paCost: 2,
    requiredLevel: 1,
    rangeMin: 0,
    rangeMax: 3,
    lineOfSight: true,
    zone: "cell",
    element: "eau",
    damageMin: 6,
    damageMax: 8,
    maxCastsPerTurn: 3,
    eryonCharges: { element: "eau", chargeGain: 1 },
    description: "Dégâts Eau légers et +1 charge Eau.",
  },
};
