export default {
  griffure: {
    id: "griffure",
    label: "Griffure",
    paCost: 3,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "agilite",
    damageMin: 8,
    damageMax: 12,
    maxCastsPerTurn: 2,
    effects: [
      { type: "damage", element: "agilite", min: 8, max: 12 },
    ],
    description: "Un coup de griffes rapide au corps a corps.",
  },
  projectile_epineux: {
    id: "projectile_epineux",
    label: "Projectile epineux",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "agilite",
    damageMin: 10,
    damageMax: 14,
    cooldownTurns: 2,
    effects: [
      { type: "damage", element: "agilite", min: 10, max: 14 },
    ],
    description: "Lance un projectile a moyenne portee (1-4 PO).",
  },
};
