export default {
  ronce: {
    id: "ronce",
    label: "Frappe de ronce",
    paCost: 3,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 7,
    damageMax: 11,
    maxCastsPerTurn: 2,
    description: "Une ronce frappe au corps a corps.",
  },
  seve_toxique: {
    id: "seve_toxique",
    label: "Sève toxique",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageOnHit: false,
    damageMin: 0,
    damageMax: 0,
    cooldownTurns: 3,
    statusEffect: {
      id: "seve_toxique",
      type: "poison",
      label: "Sève toxique",
      turns: 2,
      damageMin: 4,
      damageMax: 7,
    },
    description: "Empoisonne la cible pendant 2 tours (1-4 PO).",
  },
};

