export default {
  traction_gardien: {
    id: "traction_gardien",
    label: "Traction du gardien",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 5,
    lineOfSight: true,
    zone: "cell",
    castPattern: "line4",
    damageOnHit: false,
    damageMin: 0,
    damageMax: 0,
    pullTargetToMeleeOnHit: true,
    description: "Attire la cible en ligne vers le gardien (1-5 PO).",
  },
  gardatagarde: {
    id: "gardatagarde",
    label: "Gardatagarde",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 12,
    damageMax: 15,
    maxCastsPerTurn: 2,
    description: "Frappe terre a moyenne portee.",
  },
};
