export default {
  taille_libarene: {
    id: "taille_libarene",
    label: "Taille libarene",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 16,
    damageMax: 20,
    effects: [
      { type: "damage", element: "terre", min: 16, max: 20 },
    ],
    maxCastsPerTurn: 1,
    cooldownTurns: 2,
    description: "Frappe lourde au corps a corps.",
  },
  griffure_libarene: {
    id: "griffure_libarene",
    label: "Griffure libarene",
    paCost: 3,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 11,
    damageMax: 14,
    effects: [
      { type: "damage", element: "terre", min: 11, max: 14 },
    ],
    maxCastsPerTurn: 2,
    description: "Attaque rapide au corps a corps.",
  },
};
