export default {
  ombre_frappe: {
    id: "ombre_frappe",
    label: "Frappe obscure",
    paCost: 4,
    rangeMin: 1,
    rangeMax: 1,
    lineOfSight: true,
    zone: "cell",
    element: "terre",
    damageMin: 22,
    damageMax: 28,
    maxCastsPerTurn: 2,
    description: "Coup de melee puissant.",
  },
  ombre_rafale: {
    id: "ombre_rafale",
    label: "Rafale sombre",
    paCost: 4,
    rangeMin: 2,
    rangeMax: 4,
    lineOfSight: true,
    zone: "cell",
    element: "feu",
    damageMin: 16,
    damageMax: 20,
    maxCastsPerTurn: 1,
    description: "Attaque sombre a distance.",
  },
};
